language: minimal
script:
  - echo "Called Script"
deploy:
  - provider: script
    # edge: true in order to use the conditional deployment feature "on"
    edge: true
    script: ./push_to_ecr.sh
    on:
      tags: true 
